export const USER_MASTER_LIST = "USER_MASTER_LIST";

export const PRODUCTS_LIST = "PRODUCTS_LIST";
export const TEST_MASTER_LIST = "TEST_MASTER_LIST";
export const TEST_MASTER_LIST_BY_PRODUCT = "TEST_MASTER_LIST_BY_PRODUCT";
export const TEMPLATE_LIST = "TEMPLATE_LIST";

export const CUSTOMER_LIST = "CUSTOMER_LIST";
